"""Implementation of FbaOptimization class.

Support functions for COBRApy and gurobipy optimization of FBA models.

Peter Schubert, HHU Duesseldorf, CCB, November 2024
"""

import re

# gurobipy should not be a hard requirement, unless used in this context
try:
    import gurobipy as gp
except ImportError:
    gp = None
    pass

from .optimize import Optimize


class FbaOptimization(Optimize):
    """Support optimization of SBML encoded FBA based models generated by f2xba.

    Using the COBRApy interface for optimization of FBA/TFA models:
    Use of FbaOptimization is optional, but it can provide access to additional features, e.g. results analysis,
    and ensures correct configuration of variables and constraints for thermodynamics constraint variants.

    .. code-block:: python

        import cobrapy

        cobra_model = cobra.io.read_sbml_model('iML1515.xml')
        fo = FbaOptimization('iML1515.xml', cobra_model)
        cobra_model.medium = lb_medium
        solution = cobra_model.optimize()

    Using the gurobipy interface for optimization of FBA/TFA models:
    Note: GUROBI optimizer with gurobipy (https://www.gurobi.com) needs to be installed on your system.

    .. code-block:: python

        fo = FbaOptimization('iML1515.xml')
        fo.medium = lb_medium
        solution = fo.optimize()
    """

    def __init__(self, fname, cobra_model=None):
        """Instantiate the FbaOptimization instance.

        :param str fname: filename of the SBML coded FBA/TFA model
        :param cobra_model: reference to cobra model (default: None)
        :type cobra_model: :class:`cobra.Model`
        """
        super().__init__('FBA', fname, cobra_model)

    @property
    def medium(self):
        """Mimic medium property of COBRApy to set and retrieve medium.

        :return: exchange reaction ids with (positive valued) uptake rates
        :rtype: dict
        """
        ex_medium = {}
        for ex_rid, (lb, ub) in self.get_variable_bounds(self.uptake_rids).items():
            if lb < 0.0:
                ex_medium[re.sub('^R_', '', ex_rid)] = -lb
        return ex_medium

    @medium.setter
    def medium(self, ex_medium):
        """Mimic medium property of COBRApy for medium assignments.

        Allow assignment of medium using:
          FbaOptimization.medium = ex_medium

        :param dict ex_medium: exchange reaction ids (with/without `R_`) and (positive valued) uptake rates
        """
        self.set_medium(ex_medium)

    def gene_knock_outs(self, genes):
        """Simulate gene deletion for FBA type models.

        Block reactions that depend on the specified gene.
        In case affected reactions have a non-zero flux constraint, all objective variables are constraint to zero.

        .. code-block:: python

            orig_bounds = fo.gene_knock_outs('b0025')
            solution = fo.optimize()
            fo.set_variable_bounds(orig_bounds)
            print(f'mutant gr: {solution.objective_value:.3f} h-1')

        :param genes: gene identifiers
        :type genes: str or list(str)
        :return: original reaction bounds (lb, ub)
        :rtype: dict(str, tuple)
        """
        if type(genes) is str:
            genes = [genes]

        orig_rid_bounds = {}
        if self.is_gpm:
            update_bounds = {}
            # block related metabolic reactions if flux range allows zero flux
            for var_id, (lb, ub) in self.get_variable_bounds(self.get_rids_blocked_by(genes)).items():
                if lb <= 0.0 <= ub:
                    update_bounds[var_id] = (0.0, 0.0)
                else:
                    # block objective variables, if metabolic reaction has a non-zero flux constraint
                    update_bounds.update({rid: (0.0, 0.0) for rid in self.get_objective()[0].keys()})
            orig_rid_bounds = self.set_variable_bounds(update_bounds)
        else:
            # COBRApy gene deletion impact
            for rid in self.get_rids_blocked_by(genes):
                ridx = re.sub('^R_', '', rid)

                lb, ub = self.model.reactions.get_by_id(ridx).bounds
                if lb <= 0.0 <= ub:
                    orig_rid_bounds[ridx] = (lb, ub)
                    self.model.reactions.get_by_id(ridx).bounds = (0.0, 0.0)
                else:
                    # block objective variables, if metabolic reaction has a non-zero flux constraint
                    for ridx in self.get_objective()[0].keys():
                        orig_rid_bounds[ridx] = (lb, ub)
                        self.model.reactions.get_by_id(ridx).bounds = (0.0, 0.0)
        return orig_rid_bounds

