"""Implementation of RbaOptimization class.

Support both COBRApy and gurobipy interfaces

Note: RBA is a feasibility problem. Using a bisection algorithm as implemented in RbaPy
(Bulović et al., 2019), the highest growth rate is retrieved where the LP is still feasible.
RBA model includes variable bounds and stoichiometric coefficients that
are dependent on selected growth rate and medium.

Optimization problem related parameters need to be updated during optimization. This is performed
in according to SBML specifications using initial assignment procedures.

The class takes care of
- initial variable and constraints configuration
- extraction data configured in the SBML model, such as function definitions, initial assignments,
species references, XML annotations, Miriam annotations
- reconfiguration of optimization problem related parameters prior to each feasibility loop

Peter Schubert, HHU Duesseldorf, January 2024
"""

import re
import math
import pandas as pd
from collections import defaultdict
from scipy.optimize import minimize_scalar
import tqdm


import sbmlxdf
import f2xba.prefixes as pf
from f2xba.utils.mapping_utils import valid_sbml_sid
from .rba_initial_assignments import InitialAssignments
from .optimize import Optimize, extract_net_fluxes

# gurobipy should not be a hard requirement, unless used in this context
try:
    import gurobipy as gp
except ImportError:
    gp = None
    pass

XML_SPECIES_NS = 'http://www.hhu.de/ccb/rba/species/ns'
XML_COMPARTMENT_NS = 'http://www.hhu.de/ccb/rba/compartment/ns'


class RbaOptimization(Optimize):
    """Support optimization of SBML encoded RBA based models generated by f2xba.

    Optimization support is provided via COBRApy and guropipy interfaces for RBA models
    created by f2xba, utilizing the bisection algorithm of RbaPy (Bulović et al., 2019).

    Ref: Bulović, A., Fischer, S., Dinh, M., Golib, F., Liebermeister, W., Poirier, C., Tournier,
    L., Klipp, E., Fromion, V., & Goelzer, A. (2019). Automated generation of bacterial resource
    allocation models. Metabolic Engineering, 55, 12-22.
    https://doi.org/https://doi.org/10.1016/j.ymben.2019.06.001

    Using the COBRApy interface for optimization of RBA and TRBA models:

    .. code-block:: python

        import cobra

        cobra_model = cobra.io.read_sbml_model('iML1515_RBA.xml')
        ro = RbaOptimization('iML1515_RBA.xml', cobra_model)

        sigma = ro.avg_enz_saturation
        importer_km = ro.importer_km
        rel_mmol_per_l =  (sigma / (1.0-min(sigma, .99))) * importer_km
        ex_sidx2mmol_per_l = {re.sub('EX_', '', ex_ridx): rel_mmol_per_l for ex_ridx in lb_medium}
        ex_sidx2mmol_per_l['h_e'] = 100.0 * sigma
        ro.medium = ex_sidx2mmol_per_l

        solution = ro.solve(gr_min=0.01, gr_max=1.2, bisection_tol=1e-3)

    Using the gurobipy interface for optimization of RBA and TRBA models, providing significant speed improvements:
    Note: GUROBI optimizer with gurobipy (https://www.gurobi.com) needs to be installed on your system.

    .. code-block:: python

        ro = RbaOptimization('iML1515_RBA.xml')

        sigma = ro.avg_enz_saturation
        importer_km = ro.importer_km
        rel_mmol_per_l =  (sigma / (1.0-min(sigma, .99))) * importer_km
        ex_sidx2mmol_per_l = {re.sub('EX_', '', ex_ridx): rel_mmol_per_l for ex_ridx in lb_medium}
        ex_sidx2mmol_per_l['h_e'] = 100.0 * sigma
        ro.medium = ex_sidx2mmol_per_l

        solution = ro.solve(gr_min=0.01, gr_max=1.2, bisection_tol=1e-3)

    """

    def __init__(self, fname, cobra_model=None):
        """Instantiation of RbaOptimization instance.

        :param str fname: filename of the SBML coded extended model
        :param cobra_model: reference to cobra model (default: None)
        :type cobra_model: cobra.Model
        """
        super().__init__('RBA', fname, cobra_model)

        required = {'species', 'reactions', 'unitDefs', 'funcDefs', 'initAssign', 'parameters', 'compartments'}
        missing = required.difference(set(self.m_dict))
        if len(missing) > 0:
            print(f'Missing components {missing} in SBML document!')
            raise AttributeError

        self.df_mm_data = self._get_macromolecule_data()
        """Pandas DataFrame with macromolecule related information."""

        self.df_enz_data = self._get_enzyme_data()
        """Pandas DataFramw with enzyme molecular weights."""

        self.enz_mm_composition = self._get_enzyme_mm_composition()
        """Mapping enzyme identifiers to enzyme composition."""

        self.initial_assignments = InitialAssignments(self)
        """Initial assignments configured in the RBA model."""

        self._configure_rba_model_constraints()

        # for COBRAPy models using IBM CPLEX, switch off scaling
        if cobra_model and 'cplex' in self.model.solver.interface.__name__:
            self.model.solver.problem.parameters.read.scale.set(-1)

    @property
    def medium(self):
        """Mimic medium property of COBRApy to set and retrieve medium wrt concentrations.

        Medium concentrations returned in units of mmol/l.

        :return: metabolite concentrations in external medium in mmol/l
        :rtype: dict
        """
        ex_midx_mmol_per_l = {}
        for sid in self.ex_rid2sid.values():
            mmol_per_l = self.initial_assignments.local_env.get(sid, 0.0)
            if mmol_per_l > 0.0:
                ex_midx_mmol_per_l[re.sub(f'^{pf.M_}', '', sid)] = mmol_per_l
        return ex_midx_mmol_per_l

    @medium.setter
    def medium(self, ex_sids_mmol_per_l):
        """Mimic medium property of COBRApy for medium assignments wrt concentrations.

        Allow assignment of medium using:
          RbaOptimization.medium = ex_sids_mmol_per_l

        :param dict ex_sids_mmol_per_l: external metabolite concentrations (mmol/l)
        """
        self.set_medium_conc(ex_sids_mmol_per_l)

    def _configure_rba_model_constraints(self):
        """Configure constraints related to RBA modeling

            I.e. Enzyme forward and reverse efficiencies configured at ≤ 0.0
        """
        if self.is_gpm:
            self._gp_configure_rba_model_constraints()
        else:
            self._cp_configure_rba_model_constraints()

    def _gp_configure_rba_model_constraints(self):
        """Configure constraints related to RBA modeling for GuropiPy interface"""
        for constr in self.gpm.getConstrs():
            if re.match(pf.C_EF_, constr.ConstrName) or re.match(pf.C_ER_, constr.ConstrName):
                constr.sense = '<'
        print(f'RBA enzyme efficiency constraints configured (C_EF_xxx, C_ER_xxx) ≤ 0')

    def _cp_configure_rba_model_constraints(self):
        """Configure constraints related to RBA modeling for COBRApy interface"""
        modify_constr_bounds = {pf.C_EF_: [None, 0.0], pf.C_ER_: [None, 0.0]}
        for constr in self.model.constraints:
            for cprefix, bounds in modify_constr_bounds.items():
                if re.match(cprefix, constr.name):
                    constr.lb, constr.ub = bounds
        print(f'RBA enzyme efficiency constraints configured (C_EF_xxx, C_ER_xxx) ≤ 0')

    def configure_min_protein_conc_constraints(self):
        """Configure minimum protein concentration constraints.

        Changes the sign of protein concentration constraints 'MM_xxx' from '=' to '≥'.

        This will support optimization problems that require availability of sufficient protein to catalzye
        the reactions, i.e. protein concentration could exceed protein requirement.
        Example: are overexpressing of specific proteins.

        Protein overexpression can be implemented to configure lower bounds on protein synthesis reactioin
        variables 'R_PROD_xxx'.
        """
        if self.is_gpm:
            for constr in self.gpm.getConstrs():
                if re.match(pf.MM_, constr.ConstrName):
                    constr.sense = '>'
        else:
            for constr in self.model.constraints:
                if re.match(pf.MM_, constr.name):
                    constr.ub = 1000.0
        print(f'minimum protein constraints configured.')

    # INITIAL DATA COLLECTION PART
    def _get_macromolecule_data(self):
        data = {}
        for mm_id, row in self.m_dict['species'].iterrows():
            if re.match(pf.MM_, mm_id):
                refs = sbmlxdf.misc.get_miriam_refs(row.get('miriamAnnotation'), 'uniprot', 'bqbiol:is')
                uniprot = refs[0] if len(refs) > 0 else None
                xml_attrs = sbmlxdf.misc.extract_xml_attrs(row.get('xmlAnnotation'), ns=XML_SPECIES_NS)
                mw_aa = float(xml_attrs['weight_aa']) if 'weight_aa' in xml_attrs else None
                mw_kda = float(xml_attrs['weight_kDa']) if 'weight_kDa' in xml_attrs else None
                scale = float(xml_attrs['scale']) if 'scale' in xml_attrs else 1.0
                gp_id = re.sub(f'^{pf.MM_}', pf.G_, mm_id)
                label = self.m_dict['fbcGeneProducts']['label'].get(gp_id)
                data[mm_id] = [xml_attrs['type'], uniprot, mw_kda, mw_aa, scale, label]
        cols = ['type', 'uniprot', 'mw_kDa', 'mw_aa', 'scale', 'label']
        df = pd.DataFrame(data.values(), index=list(data), columns=cols)
        df.index.name = 'mm_id'
        return df

    def _get_enzyme_data(self):
        """Extract molecular weights of enzymes and process machines.

        From xmlAnnotation of reactions corresponding of related concentration variables

        :return: enzyme data with name, molecular weight and scaling.
        :rtype: pandas.DataFrame
        """
        enz_data = {}
        for vid, row in self.m_dict['reactions'].iterrows():
            if re.match(pf.V_EC_, vid) or re.match(pf.V_PMC_, vid):
                xml_attrs = sbmlxdf.misc.extract_xml_attrs(row.get('xmlAnnotation'), ns=XML_SPECIES_NS)
                mw_kda = float(xml_attrs['weight_kDa']) if 'weight_kDa' in xml_attrs else None
                scale = float(xml_attrs['scale']) if 'scale' in xml_attrs else 1.0
                enz_data[vid] = [mw_kda, scale]
        cols = ['mw_kDa', 'scale']
        df_enz_data = pd.DataFrame(enz_data.values(), index=list(enz_data), columns=cols)
        df_enz_data.index.name = 'id'
        return df_enz_data

    def _get_enzyme_mm_composition(self):
        """Determine macromolecule composition of enzymes and process machines (proteins and RNA).

        Note: stoichiometry wrt enzyme and process machine concentrations
        are configured in initial model considering a given model growth rate (e.g. 1.0 h-1)
        From stoichiometric coefficients we can derive enzyme/process machine composition
        wrt to macro molecules

        :return: enzyme/process machine composition wrt macromolecules
        :rtype: dict
        """
        model_gr = self.m_dict['parameters'].loc['growth_rate'].value
        enz_mm_composition = defaultdict(dict)
        for rid, row in self.m_dict['reactions'].iterrows():
            if re.match(pf.V_EC_, rid) or re.match(pf.V_PMC_, rid):
                for sref_str in sbmlxdf.record_generator(row['reactants']):
                    params = sbmlxdf.extract_params(sref_str)
                    if re.match(pf.MM_, params['species']):
                        enz_mm_composition[rid][params['species']] = float(params['stoic']) / model_gr
        return dict(enz_mm_composition)

    def set_medium_conc(self, ex_sids_mmol_per_l):
        """Configure external metabolite concentrations (mmol/l).

        In the RBA, the growth medium is defined by external metabolite concentrations (mmol/L).
        These concentrations are used to determine the media-dependent transporter saturation
        levels of the uptake reactions. This determination is made using a Michaelis-Menten type
        saturation function with a default Michaelis constant (Km) of 1.0 mmol/L.
        External media concentration should be scaled to the default Km value.
        This implementation of RBA still uses uptake reactions, which will be opened for
        the specified medium.

        :meta private:
        :param ex_sids_mmol_per_l: external metabolite concentrations (mmol/l)
        :type ex_sids_mmol_per_l: dict (key: metabolite id/str, val: concentration/float)
        """
        # remove any trailing 'M_'
        ex_sidx_mmol_per_l = {re.sub(f'^{pf.M_}', '', sid): mmol_per_l for sid, mmol_per_l in
                              ex_sids_mmol_per_l.items()}

        # unlimited uptake for metabolites in external medium
        self.set_medium({self.sidx2ex_ridx.get(sidx, 0.0): 1000.0 for sidx in ex_sidx_mmol_per_l})

        # configure RBA related medium concentrations (and set concentrations of not available medium to zero)
        medium_conc = {sid: ex_sidx_mmol_per_l.get(re.sub(f'^{pf.M_}', '', sid), 0.0)
                       for sid in self.ex_rid2sid.values()}
        self.initial_assignments.set_medium_conc(medium_conc)

    def _set_growth_rate(self, growth_rate):
        """Set growth rate dependent model parameters in RBA models

        :param float growth_rate: selected growth rate in h-1
        :return:
        """
        self.initial_assignments.set_growth_rate(growth_rate)

    @ staticmethod
    def _get_coupling_var_constr_ids(iso_rid):
        """Determine coupling data for iso reaction with enzyme efficiency.

        E.g. R_PGM_iso1 -> var_id: R_PGM_iso1, constr_id: C_EF_PGM_iso1
        E.g. R_PGM_iso1_REV -> var_id: R_PGM_iso1, constr_id: C_ER_PGM_iso1

        :param str iso_rid: reaction identifier
        :return: variable and constraint identifiers
        :rtype: str, str
        """
        iso_ridx = re.sub('^' + pf.R_, '', iso_rid)
        if re.match(r'.*_REV$', iso_ridx):
            iso_fwd_ridx = re.sub('_REV$', '', iso_ridx)
            constr_id = pf.C_ER_ + iso_fwd_ridx
        else:
            iso_fwd_ridx = iso_ridx
            constr_id = pf.C_EF_ + iso_fwd_ridx

        # in RBA models, directions are implemented reversible
        var_id = pf.R_ + iso_fwd_ridx
        return var_id, constr_id

    def _cp_scale_kcats(self, scale_kcats):
        """Scale kcat values / enzume efficiences for COBRApy interface.

        Scale related coupling coefficients.

        :param dict(str, float) scale_kcats: selected reaction ids with kcat scaling factor
        """
        self.orig_coupling = {}
        for iso_rid, scale in scale_kcats.items():
            var_id, constr_id = self._get_coupling_var_constr_ids(iso_rid)
            if (var_id in self.model.reactions) and (constr_id in self.model.metabolites):
                var = self.model.reactions.get_by_id(var_id)
                constr = self.model.metabolites.get_by_id(constr_id)
                if constr in var.metabolites:
                    orig_coupling = var.metabolites[constr]
                    self.orig_coupling[iso_rid] = orig_coupling
                    var.add_metabolites({constr: orig_coupling / scale}, combine=False)
                else:
                    print(f'scale_kcats for {iso_rid}: constraint {constr_id} not part variable {var_id}!')
            else:
                print(
                    f'scale_kcats for {iso_rid}: variable {var_id} and/or constraint {constr_id} not found in model!')

    def _cp_unscale_kcats(self):
        """Unscale kcat values / enzyme efficiencies for COBRApy interface,

        Restore original coupling coefficients
        """
        for iso_rid, coupling in self.orig_coupling.items():
            var_id, constr_id = self._get_coupling_var_constr_ids(iso_rid)
            if (var_id in self.model.reactions) and (constr_id in self.model.metabolites):
                var = self.model.reactions.get_by_id(var_id)
                constr = self.model.metabolites.get_by_id(constr_id)
                var.add_metabolites({constr: coupling}, combine=False)
        self.orig_coupling = {}

    def _gp_scale_kcats(self, scale_kcats):
        """Scale kcat values / enzume efficiencies for gurobipy interface,

        Scale related coupling coefficients.

        :param dict(str, float) scale_kcats: selected reaction ids with kcat scaling factor
        """
        self.orig_coupling = {}

        for iso_rid, scale in scale_kcats.items():
            # retrieve corresponding constr_id, considering forward and reverse directions
            var_id, constr_id = self._get_coupling_var_constr_ids(iso_rid)
            var = self.gpm.getVarByName(var_id)
            constr = self.gpm.getConstrByName(constr_id)
            if var and constr:
                orig_coupling = self.gpm.getCoeff(constr, var)
                self.orig_coupling[iso_rid] = orig_coupling
                self.gpm.chgCoeff(constr, var, orig_coupling / scale)
            else:
                print(f'scale_kcats for {iso_rid}: variable {var_id} and/or constraint {constr_id} not found!')
        self.gpm.update()

    def _gp_unscale_kcats(self):
        """Unscale kcat values for gurobipy interface, by resetting original coupling coefficients
        """
        for iso_rid, coupling in self.orig_coupling.items():
            var_id, constr_id = self._get_coupling_var_constr_ids(iso_rid)
            var = self.gpm.getVarByName(var_id)
            constr = self.gpm.getConstrByName(constr_id)
            if var and constr:
                self.gpm.chgCoeff(constr, var, coupling)
        self.gpm.update()
        self.orig_coupling = {}

    def gp_scale_variable(self, var_id, scale):
        """Scale a variable in a gurobipy model instance

            variable bounds are multiplied with scale
            coeffients are divided by scale
            initial assignments are taken care of

        :param str var_id: variable id
        :param float scale: scaling factor
        :return:
        """
        if self.is_gpm:
            if var_id in self.initial_assignments.target_rids:
                self.initial_assignments.target_rids[var_id].rescale = scale
        super().gp_scale_variable(var_id, scale)

    def get_init_assign_math(self, ia_refs):
        """Get expanded math string used in initial assignments of RBA models.

        RBA model uses initial assignments for model update during optimization.
        Model parameter values can be set depending on external media concentrations and growth rate.
        This method retrieves the expanded math for a list of initial assignment references,
        each reference contains a dictionary with the attributes:
        `var_id`: variable identifier,
        `constr_id`: constraint identifier, and
        `constr_type`: `reactants`, `products`, or `flux_bounds`.

        .. code-block:: python

            ro.get_init_assign_math([{'var_id': 'V_TSMC', 'constr_type': 'reactants', 'constr_id': 'M_hemeA_c'}])


        :param list(dict) ia_refs: reference to specific initial assignment
        :return: extended math strings
        :rtype: list(dict), like input with additional attribute 'math_str'
        """
        ia_data = []
        for data in ia_refs:
            var_id = data.get('var_id', '')
            constr_id = data.get('constr_id', '')
            constr_type = data.get('constr_type', '')

            if (var_id not in self.initial_assignments.target_rids or
                    constr_type not in ('reactants', 'products', 'flux_bounds') or
                    constr_id not in getattr(self.initial_assignments.target_rids[var_id], constr_type)):
                print(f'Invalid reference. var_id: {var_id}, constr_type: {constr_type}, constr_id: {constr_id}')
            else:
                trid = self.initial_assignments.target_rids[var_id]
                symbol_id = getattr(trid, constr_type)[constr_id]
                ia_func = self.initial_assignments.ia_functions[symbol_id]
                ia_data.append({'var_id': var_id, 'constr_type': constr_type, 'constr_id': constr_id,
                                 'math_str': ia_func.expanded_math})
        return ia_data

    def set_init_assign_math(self, ia_data):
        """Set expanded math string used in initial assignments of RBA models.

         RBA model uses initial assignments for model update during optimization.
         Model parameter values can be set depending on external media concentrations and growth rate.
         This method sets the expanded math for a list of initial assignment references,
         each reference contains a dictionary with the attributes:
         `var_id`: variable identifier,
         `constr_id`: constraint identifier,
         `constr_type`: `reactants`, `products`, or `flux_bounds`, and
         `math`: math string, e.g. `growth_rate * 0.002` or a fixed value as 0.0.

        .. code-block:: python

            ia_data_anaerobe = [{'var_id': 'V_TSMC', 'constr_type': 'reactants', 'constr_id': 'M_hemeA_c', 'math_str': '0.0'}]
            if 'EX_o2_e' not in medium:
                orig_ia_data = ro.set_init_assign_math(ia_data_anaerobe)
            solution = ro.solve(gr_min=0.01, gr_max=0.7, bisection_tol=1e-3)
            if 'EX_o2_e' not in medium:
                ro.set_init_assign_math(orig_ia_data)

         :param list(dict) ia_data: reference to specific initial assignment
         :return: the original math string, prior to modification
         :rtype: list(dict), like input, but with original math string
         """
        orig_ia_data = []
        for data in ia_data:
            var_id = data.get('var_id', '')
            constr_id = data.get('constr_id', '')
            constr_type = data.get('constr_type', '')
            new_math = str(data.get('math_str', ''))

            if (var_id not in self.initial_assignments.target_rids or
                    constr_type not in ('reactants', 'products', 'flux_bounds') or
                    constr_id not in getattr(self.initial_assignments.target_rids[var_id], constr_type) or
                    len(new_math) == 0):
                print(
                    f'Invalid record. var_id: {var_id}, constr_type: {constr_type}, constr_id: {constr_id}, math_str: {new_math}')
            else:
                trid = self.initial_assignments.target_rids[var_id]
                symbol_id = getattr(trid, constr_type)[constr_id]
                ia_func = self.initial_assignments.ia_functions[symbol_id]
                org_math = ia_func.expanded_math
                ia_func.expanded_math = new_math
                orig_ia_data.append(
                    {'var_id': var_id, 'constr_type': constr_type, 'constr_id': constr_id, 'math_str': org_math})
        return orig_ia_data

    def solve(self, gr_min=0.0, gr_max=1.5, bisection_tol=1e-5, max_iter=40):
        """Solve RBA feasibility problem using bisection algorithm.

        Support both COBRApy and gurobipy interfaces.

        :param float gr_min: minimum growth rate in h-1
        :param float gr_max: maximum growth rate in h-1
        :param float bisection_tol: stop criteria based on growth rate tolerances (default: 1e-3)
        :param int max_iter:  stop criteria based on iteration number (default: 40)
        :return: optimization solution
        :rtype: class:`Solution`
        """
        if self.is_gpm:
            return self._gp_solve(gr_min, gr_max, bisection_tol, max_iter)
        else:
            return self._cp_solve(gr_min, gr_max, bisection_tol, max_iter)

    def _gp_solve(self, gr_min, gr_max, bisection_tol, max_iter):
        """Solve RBA feasibility problem using bisection algorithm of RbaPy 1.0.

        Optionally we can modify the model to non-negative variables only.

        :param float gr_min: minimum growth rate to test in h-1, might have to be > 0.0 depending on targets
        :param float gr_max: maximum growth rate to test in h-1
        :param float bisection_tol: (optional, default 1e-3) stop criteria based on growth rate tolerances
        :param int max_iter: (optional, default 40) stop criteria based on number of iterations
        :return: optimization solution
        :rtype: class:`Solution`
        """
        # bisection algorithm to narrow in on maximum growth rate
        self._set_growth_rate(gr_min)
        solution = self.optimize()
        #if 'optimal' in solution.status:
        if solution.status == 'optimal':
            #print(f'initial gr {gr_min:.4f} h-1 obj_val: {solution.objective_value:.5f} {solution.status}')
            n_iter = 1
            while ((gr_max - gr_min) > bisection_tol) and (n_iter < max_iter):
                gr_test = gr_min + 0.5 * (gr_max - gr_min)
                self._set_growth_rate(gr_test)
                # self.gpm.reset()
                solution = self.optimize()
                # if 'optimal' in solution.status:
                if solution.status == 'optimal':
                    #print(f'step {n_iter:2d} gr: {gr_test:.4f} h-1 obj_val: {solution.objective_value:.5f} {solution.status}')
                    gr_min = gr_test
                else:
                    gr_max = gr_test
                n_iter += 1

            # collect optimization solution at optimum growth rate
            if (gr_max - gr_min) < bisection_tol:
                gr_opt = gr_min
                self._set_growth_rate(gr_opt)
                solution = self.optimize()

                # if solution with gr_min is no longer optimal, lower gr_opt slightly and try again
                # if 'optimal' not in solution.status:
                if solution.status == 'optimal':
                    gr_opt = max(0.0, gr_opt - 0.5 * bisection_tol)
                    self._set_growth_rate(gr_opt)
                    solution = self.optimize()
                #print(f'final r: {gr_opt:.4f} h-1  solution obj_val: {solution.objective_value:.5f} {solution.status}')

                solution.fluxes = extract_net_fluxes(solution.fluxes)
                solution.objective_value = gr_opt
                solution.n_iter = n_iter
                # determine final density constraint
                col = self.gpm.getCol(self.gpm.getVarByName('V_TCD'))
                solution.density_constraints = {col.getConstr(idx).constrname: -col.getCoeff(idx)
                                                for idx in range(col.size())}
            else:
                print('no optimal growth rate')

        return solution

    def _cp_solve(self, gr_min, gr_max, bisection_tol, max_iter):
        """Solve RBA feasibility problem using bisection algorithm of RbaPy 1.0.

        Use COBRApy model contexts, so we can support outer model contexts

        :param float gr_min: minimum growth rate to test in h-1, might have to be > 0.0 depending on targets
        :param float gr_max: maximum growth rate to test in h-1
        :param float bisection_tol: (optional, default 1e-3) stop criteria based on growth rate tolerances
        :param int max_iter: (optional, default 40) stop criteria based on number of iterations
        :return: optimization solution
        :rtype: class:`Solution`
        """
        # first, check feasibility a minimal (or zero) growth
        # with self.model:
        self._set_growth_rate(gr_min)
        opt_value = self.model.slim_optimize()

        # bisection algorithm to narrow in on maximum growth rate
        if math.isfinite(opt_value):
            n_iter = 1
            while ((gr_max - gr_min) > bisection_tol) and (n_iter < max_iter):
                gr_test = gr_min + 0.5 * (gr_max - gr_min)
                # with self.model:
                self._set_growth_rate(gr_test)
                opt_value = self.model.slim_optimize()
                if math.isfinite(opt_value):
                    gr_min = gr_test
                else:
                    gr_max = gr_test
                n_iter += 1

            # collect optimization solution at optimum growth rate
            if (gr_max - gr_min) < bisection_tol:
                gr_opt = gr_min
                self._set_growth_rate(gr_opt)
                solution = self.model.optimize()

                # if solution with gr_min is no longer optimal, lower gr_opt slightly and try again
                if solution.status != 'optimal':
                    gr_opt = max(0.0, gr_opt - 0.5 * bisection_tol)
                    solution = self.model.optimize()

                solution.objective_value = gr_opt
                solution.n_iter = n_iter
                solution.density_constraints = {met.id: -val for met, val
                                                in self.model.reactions.get_by_id(pf.V_TCD).metabolites.items()}
                return solution
            else:
                print('no optimal growth rate')
                return None
        else:
            print(f'Problem infeasible at minimum growth of {gr_min}')
            return None

    def gene_knock_outs(self, genes):
        """Simulate gene deletion for RBA type models.

        Block protein production reactions related to specified gene products.

        .. code-block:: python

            orig_bounds = ro.gene_knock_outs('b0025')
            solution = ro.optimize()
            ro.set_variable_bounds(orig_bounds)
            print(f'mutant gr: {solution.objective_value:.3f} h-1')

        :param genes: gene identifiers
        :type genes: str or list(str)
        :return: original reaction bounds (lb, ub)
        :rtype: dict(str, tuple)
        """

        if type(genes) is str:
            genes = [genes]

        if self.is_gpm:
            # block protein synthesis reactions of blocked genes
            update_bounds = {f'{pf.R_PROD_}{valid_sbml_sid(gene)}': (0.0, 0.0) for gene in genes}
            # block related metabolic reactions, unless an existing flux bound is violated
            for var_id, (lb, ub) in self.get_variable_bounds(self.get_rids_blocked_by(genes)).items():
                if lb <= 0.0 <= ub:
                    update_bounds[var_id] = (0.0, 0.0)
            orig_bounds = self.set_variable_bounds(update_bounds)
        else:
            # COBRApy gene deletion impact
            orig_bounds = {}
            for gene in genes:
                var_id = f'{pf.R_PROD_}{valid_sbml_sid(gene)}'
                var_idx = re.sub(f'^R_', '', var_id)
                orig_bounds[var_idx] = self.model.reactions.get_by_id(var_idx).bounds
                self.model.reactions.get_by_id(var_idx).bounds = (0.0, 0.0)
            # block related metabolic reactions, unless an existing flux bound is violated
            for rid in self.get_rids_blocked_by(genes):
                ridx = re.sub('^R_', '', rid)
                lb, ub = self.model.reactions.get_by_id(ridx).bounds
                if lb <= 0.0 <= ub:
                    orig_bounds[ridx] = (lb, ub)
                    self.model.reactions.get_by_id(ridx).bounds = (0.0, 0.0)
        return orig_bounds

    def single_gene_deletion(self, genes=None, wt_solution=None, **kwargs):
        """Perform a single gene deletion analysis for RBA based models using gurobipy interface.

        Interface aligned to COBRApy single_gene_deletion() method.
        Perform single gene deletion simulations for provided list of gene in `genes`.
        If `genes` is not provided, perform gene deletion for all genes that may be
        active in the wild type solution. In case a gene is not required in the wild type solution, a knockout
        simulation is not performed for this gene. Its growth rate value is set to the wild type value and
        its optimization status is set to `wt_solution`.
        A wild type solution can be provided with parameter `wt_solution`, alternatively a wild type solution
        is determined automatically.

        Following keyword arguments can be added to the list of parameters:
        `gr_min`: (default 0.0) minimum growth rate to test in h-1,
        `gr_min_alt`: (optional) alternative minimum growth rate in h-1 (used, if infeasible solution with gr_min),
        `gr_max`: (default 1.5) maximum growth rate to test in h-1,
        `bisection_tol`: (default 1e-5) stop criteria based on growth rate tolerance,
        `max_iter`: (default 40) stop criteria based on number of iterations.

        :param list or set genes: (optional) gene ids,
        :param :class:`Solution` wt_solution: (optional) wild type RBA solution
        :param kwargs: keyword arguments used for RBA bisectional optimization
        :return: single gene deletion results per gene with growth rate in h-1, optimization status and fitness value
        :rtype: pandas.DataFrame
        """
        if not self.is_gpm:
            print('Method implemented for gurobipy interface only.')
            return pd.DataFrame()

        alt_kwargs = kwargs.copy()
        if 'gr_min_alt' in kwargs:
            alt_kwargs['gr_min'] = kwargs.pop('gr_min_alt')
            del alt_kwargs['gr_min_alt']

        # determine wild type growth rate and fluxes, if solution not provided
        if not wt_solution:
            wt_solution = self.solve(**kwargs)
        wt_gr = wt_solution.objective_value
        #wt_fluxes = dict(RbaResults(self, {'wt': solution}).collect_fluxes()['wt'])

        all_genes = set(self.m_dict['fbcGeneProducts'].label.values)
        # tx_genes, metab_genes = self.get_tx_metab_genes()
        # pm_genes = all_genes.difference(tx_genes.union(metab_genes))

        # determine gene list, if not provided
        if not genes:
            genes = self.get_active_genes(wt_solution.fluxes)
        else:
            all_genes = genes

        # optimization loop for single gene deletions
        cols = ['growth_rate', 'status', 'fitness']
        sgko_results = {'wt': [wt_gr, 'wt_solution', 1.0]}
        for gene in tqdm.tqdm(sorted(all_genes)):
            if gene in genes:
                # simulate a single gene deletion
                self.gpm.reset()
                orig_rid_bounds = self.gene_knock_outs(gene)
                mut_solution = self.solve(**kwargs)
                # second attempt if initial attempt not optimal
                if not mut_solution or mut_solution.status != 'optimal':
                    mut_solution = self.solve(**alt_kwargs)
                # third attempt, after gpm.reset()
                if not mut_solution or mut_solution.status != 'optimal':
                    self.gpm.reset()
                    mut_solution = self.solve(**alt_kwargs)
                self.set_variable_bounds(orig_rid_bounds)

                # process simulation result
                if not mut_solution:
                    sgko_results[gene] = [0.0, 'infeasible', 0.0]
                elif mut_solution.status in {'optimal'}:
                    mutant_gr = mut_solution.objective_value
                    sgko_results[gene] = [mutant_gr, mut_solution.status, mutant_gr / wt_gr]
                else:
                    sgko_results[gene] = [0.0, mut_solution.status, 0.0]
            #elif gene in pm_genes:
            #    sgko_results[gene] = [0.0, 'process_machine']
            else:
                # genes not in gene_list are assumed to not impact the wild type solution
                sgko_results[gene] = [wt_gr, 'wt_solution', 1.0]

        df_sgko = pd.DataFrame(sgko_results.values(), index=list(sgko_results), columns=cols)
        df_sgko.index.name = 'gene'

        return df_sgko

    def _minimize_moma_objective(self, gr):
        """Method used in scipy.minimize_scalar, to minimize MOMA objective function"""
        self._set_growth_rate(gr)
        solution = self.optimize()
        obj_val = solution.objective_value
        return obj_val

    def moma(self, wt_solution, linear=False, **kwargs):
        """MOMA implementation for RBA models.

        Support gurobipy interface only.

        Ref: Segre et al. 2002, Analysis of optimality in natural and perturbed
        metabolic networks.

        :param :class:`Solution` wt_solution: wild type solution
        :param bool linear: using quadratic (Euclidean distance) or linear formulation (Manhattan) (default: False)
        :param kwargs: keyword arguments as supplied during RbaOptimization.solve()
        :return: MOMA determined solution
        :rtype: :class:`Solution`
        """
        if self.is_gpm:
            return self._gp_moma(wt_solution, linear, **kwargs)
        else:
            print('Method implemented for gurobipy interface only.')
            return pd.DataFrame()
            # return self._cp_moma(wt_solution, linear, **kwargs)

    def _gp_moma(self, wt_solution, linear=False, **kwargs):
        """MOMA implementaton for RBA models (gurobipy).

        Assumed that genetic perturbation has been added to gurobipy model instance.
        Move guropipy model instance aside, to be resored later. Create a new copy of the gurobipy model instance
        on which the MOMA specific variables, constraints and objective functions are added. These steps
        are required, as the model modifications during the RBA bisection algorithme are implemented on the
        gurobipy model instance configured in the Class.
        Determine maximal growth rate for MOMA constraint model RBA bisection algorithm. Note: RBA optimization
        will determine the maximal growth rate for a feasible solution, which will not necessarily minimize
        the MOMA objective function.
        Using scipy.optimize.minimize_scalar(), we minimize the MOMA objective within the range of feasible
        growth rates. Linear optimization (RbaOptimization.optimize()) is used instead of bisection
        algorithm (RbaOptimization.solve()).
        A MOMA solution is determined at the optimall growth rate as determined by MOMA objective minimization.
        Finaly the original gurobipy model is restored.

        :param :class:`Solution` wt_solution: wild type solution
        :param bool linear: using quadratic (Euclidean distance) or linear formulation (Manhattan) (default: False)
        :param kwargs: keyword arguments as supplied during RbaOptimization.solve().
        :return: MOMA determined solution
        :rtype: :class:`Solution`
        """
        # copy original gurobi problem (note: RbaOptimization.solve() works on self.gpm model instance)
        self.gpm.update()
        orig_gpm = self.gpm
        self.gpm = orig_gpm.copy()

        # identify variables modified during RBA optimization via initial assignments
        exclude_var_idxs = set()
        for var_id, tr in self.initial_assignments.target_rids.items():
            if tr.is_affected_by('growth_rate') and len(tr.flux_bounds) > 0:
                exclude_var_idxs.add(re.sub(f'^{pf.R_}', '', var_id))

        # implement MOMA constraints
        self._gp_add_moma(self.gpm, wt_solution, linear, exclude_var_idxs)
    
        # determine maximal growth rate for mutant with MOMA constraints
        mut_max_gr_solution = self.solve(**kwargs)
        if not mut_max_gr_solution or mut_max_gr_solution.status != 'optimal':
            self.gpm.reset()
            mut_max_gr_solution = self.solve(**kwargs)
            print('second attempt, after model reset')

        # get minimum value for objective function
        moma_solution = None
        if mut_max_gr_solution and mut_max_gr_solution.status == 'optimal':
            mut_max_gr = .99 * mut_max_gr_solution.objective_value
            # print(f'mut_max_gr: {mut_max_gr:.4f}')
            max_iter = kwargs.get('max_iter', 40)
            res = minimize_scalar(self._minimize_moma_objective, bounds=(kwargs['gr_min'], mut_max_gr),
                                  method='bounded', options={'maxiter': max_iter})
            gr_opt = res.x
            # print(f'minimum value for MOMA objective at {gr_opt:.4f} h-1 with objective value of {res.fun:.4f}')
            # get final MOMA solution with minimum of MOMA objective function
            self._set_growth_rate(gr_opt)
            moma_solution = self.optimize()
            moma_solution.fluxes = extract_net_fluxes(moma_solution.fluxes)
            moma_solution.objective_value = gr_opt
            moma_solution.n_iter = mut_max_gr_solution.n_iter
            col = self.gpm.getCol(self.gpm.getVarByName('V_TCD'))
            moma_solution.density_constraints = {col.getConstr(idx).constrname: -col.getCoeff(idx)
                                                 for idx in range(col.size())}

        # remove temporary model and revert to original gurobipy model
        self.gpm.close()
        self.gpm = orig_gpm

        return moma_solution
