"""Implementation of utility for single gene knockout analysis.

Peter Schubert, HHU Duesseldorf, November 2025
"""

import numpy as np
import pandas as pd

pred_outcome = {True: {True: 'tp', False: 'fn'},
                False: {True: 'fp', False: 'tn'}}


def confusion_matrix(act_classification, pred_classification):
    """Create a 2D confusion matrix based on actual and predicted classifications.

    Provided classifications contain a bolean value per items, e.g. gene names.

    :param dict act_classification: actual classifications (key: str, value: bolean)
    :param dict pred_classification: predicted classifications (key: str, value: bolean)
    :return: prediction results
    :rtype: dict
    """
    pred_results = {'tp': set(), 'fn': set(), 'fp': set(), 'tn': set(),
                    'recall': 0.0, 'precision': 0.0, 'specificity': 0.0, 'accuracy': 0.0, 'mcc': 0.0,
                    'cm': pd.DataFrame()}
    for gene, pred_class in pred_classification.items():
        if gene in act_classification:
            prediction = pred_outcome[act_classification[gene]][pred_class]
            pred_results[prediction].add(gene)

    tp = len(pred_results['tp'])
    fn = len(pred_results['fn'])
    fp = len(pred_results['fp'])
    tn = len(pred_results['tn'])
    pred_results['recall'] = tp / (tp + fn) if (tp + fn) > 0 else np.nan
    pred_results['precision'] = tp / (tp + fp) if (tp + fp) > 0 else np.nan
    pred_results['specificity'] = tn / (fp + tn) if (fp + tn) > 0 else np.nan
    pred_results['accuracy'] = (tp + tn) / (tp + fn + fp + tn) if (tp + fn + fp + tn) > 0 else np.nan
    pred_results['mcc'] = ((tp * tn - fp * fn) / np.sqrt((tp + fp) * (fn + tn) * (tp + fn) * (fp + tn))
                           if (tp + fp) * (fn + tn) * (tp + fn) * (fp + tn) > 0 else np.nan)
    cm = [[tp, fn],
          [fp, tn]]
    pred_results['cm'] = pd.DataFrame(cm, index=['act_pos', 'act_neg'], columns=['pred_pos', 'pred_neg'], dtype=int)
    return pred_results


def export_gene_predictions(pred_results, exp_fitness, pred_fitness, pred_status, uniprot_data, exp_mpmf, fname=None):
    """Export gene predictions, with additional information.

    Using the structure returned by confusion_matrix() a table is generated, indexed by gene id. The table will
    be written to an Excel file, if fname is provided.
    Table contains additional data, extracted from information provided in the parameters.

    Protein data is extracted from `uniprot_data`.

        from f2xba.uniprot.uniprot_data import UniprotData
        uniprot_data = UniprotData(organism_id, `data_refs`)

    For gene essentiality data set parameter exp_fitness to {}.

    :param dict pred_results: SGKO prediction results generated by confusion_matrix()
    :param dict exp_fitness: fitness data from experiment (key: gene/str, value: float), can be {}
    :param dict pred_fitness: fitness data determined from SGKO analysis (key: gene/str, value: float)
    :param dict pred_status: optimization status of SGKO predictions
    :param :class: `UniprotData` uniprot_data: Instance containing UniProt protein data for given model
    :param dict exp_mpmf: experimental values of protein mass fractions in mg/g (key: gene/str, value: float)
    :param str fname: (default: None) Excel file name to export tabel, `.xlsx`
    :return: table with prediction information per gene
    :rdata: pd.DataFrame
    """
    cols = ['gene_name', 'prediction', 'pred_fitness', 'pred_status', 'exp_fitness', 'mpmf',
            'uid', 'aa_len', 'description', 'go_processes']
    data = {}
    for pred_cat in ['fp', 'fn', 'tp', 'tn']:
        for gene in pred_results[pred_cat]:
            uid = uniprot_data.locus2uid[gene]
            prot = uniprot_data.proteins[uid]
            data[gene] = [prot.gene_name, pred_cat, pred_fitness.get(gene), pred_status.get(gene),
                          exp_fitness.get(gene),
                          exp_mpmf.get(gene), uid, prot.length, prot.protein_name, '; '.join(prot.go_processes)]
    df_predictions = pd.DataFrame(data.values(), index=list(data), columns=cols)
    df_predictions.sort_index(inplace=True)
    df_predictions.index.name = 'gene'

    # write predictions results to file
    if fname:
        with pd.ExcelWriter(fname) as writer:
            df_predictions.to_excel(writer, sheet_name='SGKO predictions')
            print(f'prediction results written to {fname}')
    return df_predictions
